const gulp = require("gulp")
const Tasks = require("./gulp.tasks")
gulp.task('clean', Tasks.clean)
gulp.task('less:compile', Tasks.lessCompile)
gulp.task('axml:compile', Tasks.axmlCompile)
gulp.task('json:compile', Tasks.jsonCompile)
gulp.task('assets:compile', Tasks.assetsCompile)
gulp.task('js:compile', Tasks.jsCompile)
gulp.task("build:compile", gulp.series(Tasks.clean, gulp.parallel(["less:compile", "axml:compile", "json:compile", "assets:compile", "js:compile"])))
gulp.task('server:watch', gulp.series('build:compile', function () {
  const { imSrc, lDirs, aDirs, JDirs, jDirs } = Tasks.getWatchConf()
  gulp.watch(imSrc, gulp.series("assets:compile"))
  gulp.watch(lDirs, gulp.series('less:compile'))
  gulp.watch(aDirs, gulp.series('axml:compile'))
  gulp.watch(JDirs, gulp.series('json:compile'))
  gulp.watch(jDirs, gulp.series('js:compile'))
}))